### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by madhead** [madhead/tyzenhaus#91]
- [ ] Ad creative
- [ ] YouTube text
- [ ] i18.properties

**Comment by TN2812** [comment]
Hi, how can I help you?

**Comment by madhead** [comment]
Hi, @TN2812!

Thank you for your interest!

How did you find out this project?

It would be great to receive some help, indeed. I'm even willing to spend a few bucks on it, that's discussable.

Recently, I've started a translation project on the Crowdin: https://crowdin.com/project/tyzenhaus. Check it out.

Being more technical, all the strings are stored in a single file: i18n/SRS/main/resources/i18n.properties, so you could just look there.

Thanks again!
