### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by madhead** [madhead/tyzenhaus#98]
- [x] Ad creative
- [x] YouTube text
- [x] Ad text
- [x] i18.properties

**Comment by NicolasGirondi** [comment]
Hello. I've just completed the Italian translation on Crowdin

**Comment by madhead** [comment]
Thank you, @NicolasGirondi!

Your translations allowed me to create an ad:

![Tyzenhaus Italian Ad](https://raw.githubusercontent.com/madhead/tyzenhaus/master/creatives/it.gif)

- [Video](https://raw.githubusercontent.com/madhead/tyzenhaus/master/creatives/it.mp4) version
- [YouTube](https://youtu.be/EYY8MEYikEU)

**Comment by NicolasGirondi** [comment]
Wow. This is so cool!
